version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - python -m pip install --upgrade pip setuptools
    - python -m pip install -r requirements.txt
    - sphinx-build -b html source $READTHEDOCS_OUTPUT/html
    - sphinx-build -b html source_cn $READTHEDOCS_OUTPUT/html/cn

python:
  install:
    - requirements: requirements.txt
